---
services:
  reverseproxy:
    container_name: smashproxy
    image: fonkykat/smashproxy
    ports:
        - 443:443
    volumes:
        - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
        - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    restart: always
  db :
    container_name: smashbdd
    image: mysql/mysql-server
    env_file:
      - bdd.env
    volumes:
      - data:/var/lib/mysql
  smash3000:
    container_name: smash3000
    image: fonkykat/smash3000
    env_file:
      - env.smash
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/smash3000?allowPublicKeyRetrieval=true&useSSL=false"
    depends_on:
      - db
  smashsocket:
    container_name: smashsocket
    image: fonkykat/smashsocket
    links:
      - smash3000
# Names our volume
volumes:
  data:
